// Code generated by ent, DO NOT EDIT.

package osnmap

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/kevindamm/wits-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldName, v))
}

// Shortname applies equality check predicate on the "shortname" field. It's identical to ShortnameEQ.
func Shortname(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldShortname, v))
}

// RoleCount applies equality check predicate on the "role_count" field. It's identical to RoleCountEQ.
func RoleCount(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldRoleCount, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldContainsFold(FieldName, v))
}

// ShortnameEQ applies the EQ predicate on the "shortname" field.
func ShortnameEQ(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldShortname, v))
}

// ShortnameNEQ applies the NEQ predicate on the "shortname" field.
func ShortnameNEQ(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNEQ(FieldShortname, v))
}

// ShortnameIn applies the In predicate on the "shortname" field.
func ShortnameIn(vs ...string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldIn(FieldShortname, vs...))
}

// ShortnameNotIn applies the NotIn predicate on the "shortname" field.
func ShortnameNotIn(vs ...string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNotIn(FieldShortname, vs...))
}

// ShortnameGT applies the GT predicate on the "shortname" field.
func ShortnameGT(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGT(FieldShortname, v))
}

// ShortnameGTE applies the GTE predicate on the "shortname" field.
func ShortnameGTE(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGTE(FieldShortname, v))
}

// ShortnameLT applies the LT predicate on the "shortname" field.
func ShortnameLT(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLT(FieldShortname, v))
}

// ShortnameLTE applies the LTE predicate on the "shortname" field.
func ShortnameLTE(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLTE(FieldShortname, v))
}

// ShortnameContains applies the Contains predicate on the "shortname" field.
func ShortnameContains(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldContains(FieldShortname, v))
}

// ShortnameHasPrefix applies the HasPrefix predicate on the "shortname" field.
func ShortnameHasPrefix(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldHasPrefix(FieldShortname, v))
}

// ShortnameHasSuffix applies the HasSuffix predicate on the "shortname" field.
func ShortnameHasSuffix(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldHasSuffix(FieldShortname, v))
}

// ShortnameEqualFold applies the EqualFold predicate on the "shortname" field.
func ShortnameEqualFold(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEqualFold(FieldShortname, v))
}

// ShortnameContainsFold applies the ContainsFold predicate on the "shortname" field.
func ShortnameContainsFold(v string) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldContainsFold(FieldShortname, v))
}

// RoleCountEQ applies the EQ predicate on the "role_count" field.
func RoleCountEQ(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldEQ(FieldRoleCount, v))
}

// RoleCountNEQ applies the NEQ predicate on the "role_count" field.
func RoleCountNEQ(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNEQ(FieldRoleCount, v))
}

// RoleCountIn applies the In predicate on the "role_count" field.
func RoleCountIn(vs ...int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldIn(FieldRoleCount, vs...))
}

// RoleCountNotIn applies the NotIn predicate on the "role_count" field.
func RoleCountNotIn(vs ...int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldNotIn(FieldRoleCount, vs...))
}

// RoleCountGT applies the GT predicate on the "role_count" field.
func RoleCountGT(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGT(FieldRoleCount, v))
}

// RoleCountGTE applies the GTE predicate on the "role_count" field.
func RoleCountGTE(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldGTE(FieldRoleCount, v))
}

// RoleCountLT applies the LT predicate on the "role_count" field.
func RoleCountLT(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLT(FieldRoleCount, v))
}

// RoleCountLTE applies the LTE predicate on the "role_count" field.
func RoleCountLTE(v int) predicate.OsnMap {
	return predicate.OsnMap(sql.FieldLTE(FieldRoleCount, v))
}

// HasMatches applies the HasEdge predicate on the "matches" edge.
func HasMatches() predicate.OsnMap {
	return predicate.OsnMap(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MatchesTable, MatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMatchesWith applies the HasEdge predicate on the "matches" edge with a given conditions (other predicates).
func HasMatchesWith(preds ...predicate.Match) predicate.OsnMap {
	return predicate.OsnMap(func(s *sql.Selector) {
		step := newMatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OsnMap) predicate.OsnMap {
	return predicate.OsnMap(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OsnMap) predicate.OsnMap {
	return predicate.OsnMap(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OsnMap) predicate.OsnMap {
	return predicate.OsnMap(sql.NotPredicates(p))
}
