// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kevindamm/wits-go/ent/match"
	"github.com/kevindamm/wits-go/ent/osnmap"
	"github.com/kevindamm/wits-go/ent/playerrole"
)

// MatchCreate is the builder for creating a Match entity.
type MatchCreate struct {
	config
	mutation *MatchMutation
	hooks    []Hook
}

// SetMatchHash sets the "match_hash" field.
func (mc *MatchCreate) SetMatchHash(s string) *MatchCreate {
	mc.mutation.SetMatchHash(s)
	return mc
}

// SetVersion sets the "version" field.
func (mc *MatchCreate) SetVersion(i int) *MatchCreate {
	mc.mutation.SetVersion(i)
	return mc
}

// SetSeason sets the "season" field.
func (mc *MatchCreate) SetSeason(i int8) *MatchCreate {
	mc.mutation.SetSeason(i)
	return mc
}

// SetNillableSeason sets the "season" field if the given value is not nil.
func (mc *MatchCreate) SetNillableSeason(i *int8) *MatchCreate {
	if i != nil {
		mc.SetSeason(*i)
	}
	return mc
}

// SetCreatedTs sets the "created_ts" field.
func (mc *MatchCreate) SetCreatedTs(t time.Time) *MatchCreate {
	mc.mutation.SetCreatedTs(t)
	return mc
}

// SetNillableCreatedTs sets the "created_ts" field if the given value is not nil.
func (mc *MatchCreate) SetNillableCreatedTs(t *time.Time) *MatchCreate {
	if t != nil {
		mc.SetCreatedTs(*t)
	}
	return mc
}

// SetTurnCount sets the "turn_count" field.
func (mc *MatchCreate) SetTurnCount(i int) *MatchCreate {
	mc.mutation.SetTurnCount(i)
	return mc
}

// SetFetchStatus sets the "fetch_status" field.
func (mc *MatchCreate) SetFetchStatus(ms match.FetchStatus) *MatchCreate {
	mc.mutation.SetFetchStatus(ms)
	return mc
}

// SetNillableFetchStatus sets the "fetch_status" field if the given value is not nil.
func (mc *MatchCreate) SetNillableFetchStatus(ms *match.FetchStatus) *MatchCreate {
	if ms != nil {
		mc.SetFetchStatus(*ms)
	}
	return mc
}

// SetMapID sets the "map" edge to the OsnMap entity by ID.
func (mc *MatchCreate) SetMapID(id int) *MatchCreate {
	mc.mutation.SetMapID(id)
	return mc
}

// SetNillableMapID sets the "map" edge to the OsnMap entity by ID if the given value is not nil.
func (mc *MatchCreate) SetNillableMapID(id *int) *MatchCreate {
	if id != nil {
		mc = mc.SetMapID(*id)
	}
	return mc
}

// SetMap sets the "map" edge to the OsnMap entity.
func (mc *MatchCreate) SetMap(o *OsnMap) *MatchCreate {
	return mc.SetMapID(o.ID)
}

// AddRoleIDs adds the "roles" edge to the PlayerRole entity by IDs.
func (mc *MatchCreate) AddRoleIDs(ids ...int) *MatchCreate {
	mc.mutation.AddRoleIDs(ids...)
	return mc
}

// AddRoles adds the "roles" edges to the PlayerRole entity.
func (mc *MatchCreate) AddRoles(p ...*PlayerRole) *MatchCreate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return mc.AddRoleIDs(ids...)
}

// Mutation returns the MatchMutation object of the builder.
func (mc *MatchCreate) Mutation() *MatchMutation {
	return mc.mutation
}

// Save creates the Match in the database.
func (mc *MatchCreate) Save(ctx context.Context) (*Match, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MatchCreate) SaveX(ctx context.Context) *Match {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MatchCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MatchCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MatchCreate) defaults() {
	if _, ok := mc.mutation.Season(); !ok {
		v := match.DefaultSeason
		mc.mutation.SetSeason(v)
	}
	if _, ok := mc.mutation.CreatedTs(); !ok {
		v := match.DefaultCreatedTs()
		mc.mutation.SetCreatedTs(v)
	}
	if _, ok := mc.mutation.FetchStatus(); !ok {
		v := match.DefaultFetchStatus
		mc.mutation.SetFetchStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MatchCreate) check() error {
	if _, ok := mc.mutation.MatchHash(); !ok {
		return &ValidationError{Name: "match_hash", err: errors.New(`ent: missing required field "Match.match_hash"`)}
	}
	if _, ok := mc.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Match.version"`)}
	}
	if _, ok := mc.mutation.Season(); !ok {
		return &ValidationError{Name: "season", err: errors.New(`ent: missing required field "Match.season"`)}
	}
	if _, ok := mc.mutation.CreatedTs(); !ok {
		return &ValidationError{Name: "created_ts", err: errors.New(`ent: missing required field "Match.created_ts"`)}
	}
	if _, ok := mc.mutation.TurnCount(); !ok {
		return &ValidationError{Name: "turn_count", err: errors.New(`ent: missing required field "Match.turn_count"`)}
	}
	if _, ok := mc.mutation.FetchStatus(); !ok {
		return &ValidationError{Name: "fetch_status", err: errors.New(`ent: missing required field "Match.fetch_status"`)}
	}
	if v, ok := mc.mutation.FetchStatus(); ok {
		if err := match.FetchStatusValidator(v); err != nil {
			return &ValidationError{Name: "fetch_status", err: fmt.Errorf(`ent: validator failed for field "Match.fetch_status": %w`, err)}
		}
	}
	return nil
}

func (mc *MatchCreate) sqlSave(ctx context.Context) (*Match, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MatchCreate) createSpec() (*Match, *sqlgraph.CreateSpec) {
	var (
		_node = &Match{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(match.Table, sqlgraph.NewFieldSpec(match.FieldID, field.TypeInt))
	)
	if value, ok := mc.mutation.MatchHash(); ok {
		_spec.SetField(match.FieldMatchHash, field.TypeString, value)
		_node.MatchHash = value
	}
	if value, ok := mc.mutation.Version(); ok {
		_spec.SetField(match.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := mc.mutation.Season(); ok {
		_spec.SetField(match.FieldSeason, field.TypeInt8, value)
		_node.Season = value
	}
	if value, ok := mc.mutation.CreatedTs(); ok {
		_spec.SetField(match.FieldCreatedTs, field.TypeTime, value)
		_node.CreatedTs = &value
	}
	if value, ok := mc.mutation.TurnCount(); ok {
		_spec.SetField(match.FieldTurnCount, field.TypeInt, value)
		_node.TurnCount = value
	}
	if value, ok := mc.mutation.FetchStatus(); ok {
		_spec.SetField(match.FieldFetchStatus, field.TypeEnum, value)
		_node.FetchStatus = &value
	}
	if nodes := mc.mutation.MapIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   match.MapTable,
			Columns: []string{match.MapColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(osnmap.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.osn_map_matches = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   match.RolesTable,
			Columns: match.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerrole.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MatchCreateBulk is the builder for creating many Match entities in bulk.
type MatchCreateBulk struct {
	config
	err      error
	builders []*MatchCreate
}

// Save creates the Match entities in the database.
func (mcb *MatchCreateBulk) Save(ctx context.Context) ([]*Match, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Match, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MatchMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MatchCreateBulk) SaveX(ctx context.Context) []*Match {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MatchCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MatchCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
