// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Match is the predicate function for match builders.
type Match func(*sql.Selector)

// OsnMap is the predicate function for osnmap builders.
type OsnMap func(*sql.Selector)

// Player is the predicate function for player builders.
type Player func(*sql.Selector)

// PlayerRole is the predicate function for playerrole builders.
type PlayerRole func(*sql.Selector)
